# Generated by Django 4.0.10 on 2023-08-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'The Authors'},
        ),
    ]
