# Generated by Django 4.0.10 on 2023-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_alter_author_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('nbQuestionsByMonth', models.IntegerField()),
            ],
            options={
                'db_table': 'app_questionsummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorClone',
            fields=[
            ],
            options={
                'verbose_name_plural': 'The Authors clone',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sample_app.author',),
        ),
    ]
